# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ncg-transform"
client_id = "6e776e5c13cd8cb0aa631f32d1bfc539"
application_url = "https://blood-separate-were-premium.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products, write_cart_transforms"

[auth]
redirect_urls = [
  "https://blood-separate-were-premium.trycloudflare.com/auth/callback",
  "https://blood-separate-were-premium.trycloudflare.com/auth/shopify/callback",
  "https://blood-separate-were-premium.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "deks-tech-theme.myshopify.com"
