# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1cfc220093b3ad2f7d10c93ac8e81af2"
name = "ngc-discount-test"
handle = "ngc-discount-test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "ncg-test-environment.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
