# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccd6dca5cef9a6768abf3f13bf48e944"
name = "ncg-transform-dev"
handle = "ncg-transform-dev"
application_url = "https://biological-seas-cancelled-graphs.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ncg-test-environment.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products, write_cart_transforms"

[auth]
redirect_urls = [
  "https://biological-seas-cancelled-graphs.trycloudflare.com/auth/callback",
  "https://biological-seas-cancelled-graphs.trycloudflare.com/auth/shopify/callback",
  "https://biological-seas-cancelled-graphs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
