# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f404af1e76982f1a10766b3adebeb486"
name = "ncg-transform-debug"
handle = "ncg-transform-debug"
application_url = "https://leg-vol-shall-rise.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dekstech-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_products,write_cart_transforms,write_discounts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://leg-vol-shall-rise.trycloudflare.com/auth/callback",
  "https://leg-vol-shall-rise.trycloudflare.com/auth/shopify/callback",
  "https://leg-vol-shall-rise.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
