# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "952fc59953bdc2206b9ead351b810388"
name = "ncg-transform-dev"
handle = "ncg-transform-dev"
application_url = "https://how-feels-suggested-evaluation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dekstech-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://how-feels-suggested-evaluation.trycloudflare.com/auth/callback",
  "https://how-feels-suggested-evaluation.trycloudflare.com/auth/shopify/callback",
  "https://how-feels-suggested-evaluation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
