# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e776e5c13cd8cb0aa631f32d1bfc539"
name = "ncg-transform"
handle = "ncg-transform"
application_url = "https://ncg-transform-916f30131d4e.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "ncg-test-environment.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://ncg-transform-916f30131d4e.herokuapp.com/auth/callback",
  "https://ncg-transform-916f30131d4e.herokuapp.com/auth/shopify/callback",
  "https://ncg-transform-916f30131d4e.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
