api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "discount-allocator"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.discounts-allocator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "yarn build"
  path = "dist/function.wasm"

  [extensions.ui.paths]
[extensions.ui.paths]
  create = "/app/discount-allocator/:functionId/new"
  details = "/app/discount-allocator/:functionId/:id"
